OCHamcrest: HCOrderingComparison Class Reference
HCOrderingComparison Class Reference
Inherits HCBaseMatcher.
Public Member Functions
(id) - initComparing:minCompare:maxCompare:
Static Public Member Functions
(HCOrderingComparison *) + compare:minCompare:maxCompare:
Protected Attributes
id value
NSComparisonResult minCompare
NSComparisonResult maxCompare
Member Function Documentation
+ (HCOrderingComparison *) compare: (id) aValue minCompare: (NSComparisonResult) min maxCompare: (NSComparisonResult) max
Referenced by HC_greaterThan(), HC_greaterThanOrEqualTo(), HC_lessThan(), and HC_lessThanOrEqualTo().
- (id) initComparing: (id) aValue minCompare: (NSComparisonResult) min maxCompare: (NSComparisonResult) max
References maxCompare, minCompare, and value.
Member Data Documentation
- (NSComparisonResult) maxCompare [protected]
Referenced by initComparing:minCompare:maxCompare:.
- (NSComparisonResult) minCompare [protected]
Referenced by initComparing:minCompare:maxCompare:.
- (id) value [protected]
Referenced by initComparing:minCompare:maxCompare:.