DOCSET_NAME=org.hamcrest.OCHamcrest.docset
DESTDIR=~/Library/Developer/Shared/Documentation/DocSets

install:
	mkdir -p $(DESTDIR)
	cp -R $(DOCSET_NAME) $(DESTDIR)

uninstall:
	rm -rf $(DESTDIR)/$(DOCSET_NAME)
